In [2]:
from typing import Tuple,List
import math
import random 
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
def uniform_pdf(x:float)->float:
    return 1 if 0<=x<=1 else 0


def uniform_cdf(x:float)->float:
    if x<0 :return 0
    if  0<=x<=1 :return x 
    if x>0: return 1
    
def normal_pdf(x:float,mu:float=0,sigma:float=1)->float:
    sqr2pi=math.sqrt(2*math.pi)
    return math.exp(-(x-mu)**2/2/sigma**2)/(sqr2pi*sigma)


def normal_cdf(x:float,mu:float=0,sigma:float=1)->float:
    return (1+math.erf((x-mu)/math.sqrt(2)/sigma))/2

def inverse_normal_cdf(p:float,mu:float=0,sigma:float=1,tolerance=0.000000001)->float:
    if mu!=0 or sigma!=1:return mu+sigma*inverse_normal_cdf(p,tolerance=tolerance)
    high=10;low=-10
    while high-low>tolerance:
            mid_z=(high+low)/2
            mid_p=normal_cdf(mid_z)
            if mid_p<p:low=mid_z
            else:high=mid_z
            
    return mid_z

In [4]:
xs=[inverse_normal_cdf(x/1000,23.4,1) for x in range(1,999)]
df=pd.DataFrame({'AGE':xs})

In [5]:
#Comparison of normal and flatfoot pressure value in static trials

S1=[inverse_normal_cdf(x/1000,0.00462,0.00205) for x in range(3,997)]
S2=[inverse_normal_cdf(x/1000,0.00931,0.00261) for x in range(3,997)]
S3=[inverse_normal_cdf(x/1000,0.00342,0.00108) for x in range(3,997)]
S4=[inverse_normal_cdf(x/1000,0.01371,0.00469) for x in range(3,997)]
S5=[inverse_normal_cdf(x/1000,0.00024,0.00059) for x in range(3,997)]

Ndf=pd.DataFrame({'sensor1':S1,'sensor2':S2,'sensor3':S3,'sensor4':S4,'sensor5':S5,'label':0})
Ndf=Ndf[(Ndf['sensor1']>0) & (Ndf['sensor3']>0) &(Ndf['sensor4']>0) & (Ndf['sensor5']>0)]
Ndf.index = np.arange(0, len(Ndf) )

#*******************

s1=[inverse_normal_cdf(x/1000,0.00929,0.00456) for x in range(3,997)]
s2=[inverse_normal_cdf(x/1000,0.00124,0.00347) for x in range(3,997)]
s3=[inverse_normal_cdf(x/1000,0.00088,0.00397) for x in range(3,997)]
s4=[inverse_normal_cdf(x/1000,0.01765,0.00311) for x in range(3,997)]
s5=[inverse_normal_cdf(x/1000,0.00676,0.00477) for x in range(3,997)]

Pdf=pd.DataFrame({'sensor1':s1,'sensor2':s2,'sensor3':s3,'sensor4':s4,'sensor5':s5,'label':1})
Pdf=Pdf[(Pdf['sensor1']>0) & (Pdf['sensor3']>0) &(Pdf['sensor4']>0) & (Pdf['sensor5']>0)]
Pdf.index = np.arange(0, len(Pdf) )

#Compine&shuffle both dataframes

frames=[Pdf,Ndf]
test=pd.concat(frames)
test = test.sample(frac = 1)
test.index = np.arange(0, len(test) )

In [6]:
file_name='project_dataset.xlsx'
test.to_excel(file_name)

In [7]:
test

       sensor1   sensor2   sensor3   sensor4   sensor5  label
0     0.005118  0.009944  0.003682  0.014850  0.000383      0
1     0.005306  0.010183  0.003781  0.015279  0.000437      0
2     0.011233  0.002719  0.002572  0.018975  0.008793      1
3     0.011721  0.003090  0.002996  0.019308  0.009303      1
4     0.004357  0.008975  0.003282  0.013109  0.000164      0
...        ...       ...       ...       ...       ...    ...
1233  0.005050  0.009857  0.003646  0.014693  0.000364      0
1234  0.013881  0.004734  0.004877  0.020781  0.011563      1
1235  0.011774  0.003130  0.003042  0.019344  0.009358      1
1236  0.006684  0.011938  0.004507  0.018432  0.000834      0
1237  0.008476  0.014219  0.005451  0.022531  0.001350      0

[1238 rows x 6 columns]